title: Lester Thomas
author: Lester Thomas
email: lester.thomas@vodafone.com
description: > # this means to ignore newlines until "baseurl:"
  Chief Systems Architect and Vodafone Distinguished Engineer. 
# social links
twitter_username: Lester_Thomas
github_username:  lesterthomas

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
