title: config title
author: Lester Thomas
email: lester.thomas@vodafone.com
description: > # this means to ignore newlines until "baseurl:"
  config description
# social links
twitter_username: @LesterThomas
github_username:  lesterthomas

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
